export const questions = [
  { id: 'q01', type: 'single', topic: 'HTML', prompt: 'В какой строке содержатся только строчные (inline) элементы?', options: [['a', '<a> <span> <textarea> <button>'], ['b', '<a> <li> <span> <img>'], ['c', '<div> <p> <video> <ol>'], ['d', '<header> <section> <a> <input>']] },
  { id: 'q02', type: 'text', topic: 'HTML', prompt: 'Чем отличается относительная ссылка от абсолютной?', placeholder: 'Напишите ответ своими словами…' },
  { id: 'q03', type: 'single', topic: 'CSS', prompt: 'За какую ось отвечает `align-items`, когда задано `flex-direction: column`?', options: [['a', 'По вертикали (Y)'], ['b', 'По горизонтали (X)'], ['c', 'За расстояние между элементами'], ['d', 'За перенос элементов на новую строку']] },
  { id: 'q04', type: 'single', topic: 'CSS', prompt: 'Чем отличается `max-width` от `width`?', options: [['a', '`width` задаёт ширину элемента, а `max-width` ограничивает её сверху'], ['b', '`width` задаёт максимальную ширину, а `max-width` — минимальную'], ['c', '`width` работает только для блочных элементов, а `max-width` — только для строчных'], ['d', '`max-width` всегда задаёт точную ширину и переопределяет `width`']] },
  { id: 'q05', type: 'single', topic: 'CSS', prompt: 'Какое значение у свойства `position` используется по умолчанию?', options: [['a', '`absolute`'], ['b', '`static`'], ['c', '`sticky`'], ['d', '`relative`']] },
  { id: 'q06', type: 'single', topic: 'CSS', prompt: 'Чем отличаются Flexbox и Grid?', options: [['a', 'Flexbox предназначен для одномерной раскладки по строке или столбцу, а Grid — для двумерной раскладки по строкам и столбцам'], ['b', 'Flexbox работает только с блочными элементами, а Grid — только со строчными'], ['c', 'Flexbox задаёт расположение по двум осям, а Grid — только по одной'], ['d', 'Flexbox используется только для адаптивной вёрстки, а Grid — только для фиксированной сетки']] },
  { id: 'q07', type: 'text', topic: 'CSS', prompt: 'Напишите CSS-правила, чтобы расположить абсолютно позиционированный дочерний элемент по центру родителя по горизонтали и вертикали. У родителя задано `position: relative`.', placeholder: 'Напишите CSS-свойства и значения…', code: '.parent { position: relative; }\n.child  { position: absolute; }' },
  { id: 'q08', type: 'fields', topic: 'JavaScript', prompt: 'Опишите, чем отличаются ключевые слова `const`, `let`, `var` и `while`.', fields: ['const', 'let', 'var', 'while'], reference: 'Для проверки: const — неизменяемая переменная; let — локальная переменная; var — глобальная переменная; while — это не переменная.' },
  { id: 'q09', type: 'multi', topic: 'JavaScript', prompt: 'Какие из функций вернут результат, который можно использовать в другом месте кода? Выберите один или несколько вариантов.', code: 'function calculateDeliveryCost(order) {\n  let cost = 5;\n  for (const item of order.items) {\n    if (item.isLarge) cost += 3;\n  }\n  if (order.isExpress) cost *= 2;\n  return cost;\n}\n\nfunction printOrderSummary(order) {\n  let itemCount = 0;\n  for (const item of order.items) itemCount += item.quantity;\n  const message = `${order.customerName}: ${itemCount} товаров`;\n  console.log(message);\n}\n\nfunction findProduct(products, productId) {\n  for (const product of products) {\n    if (product.id === productId) return product;\n  }\n  return null;\n}\n\nfunction calculateAverage(scores) {\n  let total = 0;\n  for (let i = 0; i < scores.length; i++) total += scores[i];\n  const average = scores.length ? total / scores.length : 0;\n  console.log(`Средний балл: ${average}`);\n}', options: [['a', 'calculateDeliveryCost'], ['b', 'printOrderSummary'], ['c', 'findProduct'], ['d', 'calculateAverage']] },
  { id: 'q10', type: 'single', topic: 'JavaScript', prompt: "Что вернёт функция `isNaN()`, если передать ей строку `'Hello'`?", options: [['a', '`false`'], ['b', '`NaN`'], ['c', '`true`'], ['d', '`Hello`']] },
  { id: 'q11', type: 'single', topic: 'JavaScript', prompt: 'К какому виду относится функция в выражении `const name = function() {}`?', options: [['a', 'permission'], ['b', 'declaration'], ['c', 'expression'], ['d', 'arrow']] },
  { id: 'q12', type: 'single', topic: 'JavaScript / DOM', prompt: 'С помощью какого метода можно проверить наличие класса у элемента?', options: [['a', '`has()`'], ['b', '`contains()`'], ['c', '`is()`'], ['d', '`includes()`']] },
  { id: 'q13', type: 'single', topic: 'JavaScript', prompt: 'Сколько потоков используется для выполнения JavaScript-кода в основном потоке?', options: [['a', 'Однопоточный'], ['b', 'Многопоточный'], ['c', 'У него нет потоков'], ['d', 'Трёхпоточный']] },
  { id: 'q14', type: 'single', topic: 'JavaScript / DOM', prompt: 'Что такое DOM?', options: [['a', 'Объектная модель документа: представление HTML-документа в виде дерева объектов, с которыми можно работать через JavaScript'], ['b', 'Объектная модель CSS: дерево стилей и правил, по которым браузер оформляет страницу'], ['c', 'Объектная модель браузера: интерфейсы для управления окном, вкладками и адресной строкой'], ['d', 'Дерево React-компонентов, которое создаётся при разборе JSX']] },
  { id: 'q15', type: 'single', topic: 'JavaScript', prompt: 'Что нужно написать перед функцией, чтобы использовать в ней ключевое слово `await`?', options: [['a', '`sync`'], ['b', '`*`'], ['c', '`async`'], ['d', 'Нет правильного ответа']] },
  { id: 'q16', type: 'single', topic: 'JavaScript', prompt: 'Какая встроенная функция JavaScript позволяет отправлять запросы?', options: [['a', '`axios()`'], ['b', '`query()`'], ['c', '`fetch()`'], ['d', '`send()`']] },
  { id: 'q17', type: 'single', topic: 'JavaScript', prompt: 'Сколько состояний бывает у `Promise`?', options: [['a', '1'], ['b', '2'], ['c', '3'], ['d', '4']] },
  { id: 'q18', type: 'single', topic: 'JavaScript', prompt: 'Что означает состояние промиса `rejected`?', options: [['a', 'Промис ещё ожидает завершения'], ['b', 'Промис успешно выполнен'], ['c', 'Промис отклонён или завершился с ошибкой'], ['d', 'Промис был отменён']] },
  { id: 'q19', type: 'single', topic: 'JavaScript', prompt: 'Сколько аргументов получает callback-функция в методах массивов `forEach`, `map`, `filter` и `find`?', options: [['a', 'Один'], ['b', 'Два'], ['c', 'Три'], ['d', 'Четыре']] },
  { id: 'q20', type: 'single', topic: 'JavaScript / DOM', prompt: 'Нужно обратиться к каждому элементу и вывести его текст в консоль. Какой метод можно напрямую использовать для `skills`?', code: '<ul>\n  <li class="skill">HTML</li>\n  <li class="skill">CSS</li>\n  <li class="skill">JavaScript</li>\n  <li class="skill">React</li>\n</ul>\n\nconst skills = document.querySelectorAll(".skill");', options: [['a', '`forEach`'], ['b', '`map`'], ['c', '`filter`'], ['d', '`reduce`']] },
  { id: 'q21', type: 'single', topic: 'JavaScript', prompt: 'Сколько аргументов можно передать функции?', options: [['a', 'В функции нельзя передавать аргументы'], ['b', 'Ровно столько, сколько указано в объявлении функции'], ['c', 'Нет правильного ответа'], ['d', 'Сколько указано в объявлении функции либо меньше'], ['e', 'Любое количество аргументов можно передать в функцию']] },
  { id: 'q22', type: 'single', topic: 'HTML', prompt: 'Как вставить картинку в HTML?', options: [['a', '`<img src="http://site.com/image.jpg">`'], ['b', '`<img source="http://site.com/image.jpg">`'], ['c', '`<img>src="http://site.com/image.jpg"</img>`'], ['d', '`<img src="http://site.com/image.jpg"></img>`']] },
  { id: 'q23', type: 'single', topic: 'HTML', prompt: 'Какой атрибут тега `<button>` задаёт видимый текст внутри кнопки?', options: [['a', '`value`'], ['b', '`placeholder`'], ['c', '`type`'], ['d', '`title`'], ['e', 'Ни один: текст задаётся содержимым между `<button>` и `</button>`']] },
  { id: 'q24', type: 'single', topic: 'JavaScript', prompt: 'Выберите, что из перечисленного нельзя хранить в массивах.', options: [['a', '`null`'], ['b', 'Объекты'], ['c', 'Функции'], ['d', 'Другие массивы'], ['e', 'Всё перечисленное можно хранить в массиве']] },
  { id: 'q25', type: 'single', topic: 'React', prompt: 'Какой хук позволяет создать реактивное состояние?', options: [['a', '`useEffect`'], ['b', '`useContext`'], ['c', '`useRef`'], ['d', '`useState`']] },
  { id: 'q26', type: 'single', topic: 'React', prompt: 'Для чего нужен React Fragment?', options: [['a', 'У React-компонента всегда должен быть один родитель'], ['b', 'Для реактивности'], ['c', 'Без него не будут работать хуки'], ['d', 'Для передачи `props` всем вложенным компонентам']] },
  { id: 'q27', type: 'single', topic: 'React', prompt: 'Что такое `props`?', options: [['a', 'Способ передачи данных от родительского компонента дочернему'], ['b', 'Способ передачи данных от дочернего компонента родительскому'], ['c', 'Хук для подключения к DOM-элементу'], ['d', 'Объект, в котором компонент хранит своё локальное состояние']] },
  { id: 'q28', type: 'single', topic: 'React', prompt: 'Как называется способ вставить JavaScript-выражение в JSX?', options: [['a', 'Наследование'], ['b', 'Инкапсуляция'], ['c', 'Интерполяция'], ['d', 'Полиморфизм']] },
  { id: 'q29', type: 'single', topic: 'React', prompt: "Дано выражение `const [skill, setSkill] = useState(['html', 'css'])`. Как добавить в массив слово `'js'`?", options: [['a', "`setSkill('js')`"], ['b', "`setSkill(...skill, 'js')`"], ['c', "`skill.push('js')`"], ['d', "`setSkill([...skill, 'js'])`"]] },
  { id: 'q30', type: 'single', topic: 'React', prompt: 'Выберите вариант, где `useEffect` срабатывает один раз.', options: [['a', '`useEffect(() => {}, [])`'], ['b', '`useEffect(() => {}, )`'], ['c', '`useEffect(() => {}, [1])`']] },
  { id: 'q31', type: 'single', topic: 'React', prompt: 'Как много компонентов может быть на сайте?', options: [['a', 'Не более 100'], ['b', 'Неограниченное количество'], ['c', 'Не более 10'], ['d', 'Не более 300']] },
  { id: 'q32', type: 'single', topic: 'React', prompt: 'Что такое JSX?', options: [['a', 'Расширение синтаксиса JavaScript, которое позволяет описывать интерфейс с помощью HTML-подобной разметки'], ['b', 'Отдельный язык на основе HTML, который браузер выполняет напрямую'], ['c', 'Библиотека React для управления состоянием компонентов'], ['d', 'Формат записи CSS-стилей внутри JavaScript-кода']] },
  { id: 'q33', type: 'single', topic: 'React', prompt: 'Почему в React для отображения элементов массива часто используют метод `map()`?', options: [['a', 'Он создаёт новый массив React-элементов, преобразуя каждый элемент исходного массива'], ['b', 'Он сортирует элементы массива перед отображением'], ['c', 'Он добавляет каждый элемент напрямую в DOM'], ['d', 'Он удаляет из массива повторяющиеся элементы']] },
  { id: 'q34', type: 'text', topic: 'Git / GitHub', prompt: 'Вы закончили работу над новой функцией. Опишите последовательность действий, чтобы создать отдельную ветку, сохранить изменения коммитом и отправить её на GitHub.', placeholder: 'Опишите шаги и команды…', code: 'Создать ветку → сохранить изменения → отправить ветку на GitHub' },
  { id: 'q35', type: 'text', topic: 'SCSS', prompt: 'Чем отличается обычный SCSS от модульного SCSS?', placeholder: 'Напишите ответ своими словами…' }
];

export function shuffle(list) {
  const copy = [...list];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
